System.InvalidOperationException: 'The entity type 'TipoContatoModel' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'.